### ISSUE TITLE
Browser extension does not work 

### ISSUE THREAD

**Issue by ZorinFoss** [AminBhst/brisk-browser-extension#2]
Hi,

Browser extension does not work on chromium browser (*ex.* Brave)

[sample1](https://www.7-zip.org/a/7z2301-x64.exe)
[sample2](https://github.com/AminBhst/brisk/releases/download/v1.4.3/Brisk-1.4.3-windows-x86_64.exe)

**Comment by AminBhst** [comment]
Hey @ZorinFoss. Sorry for the late response. I have been extremely busy these past couple of months. Do you still have the same problem? I tried it myself on brave and chromium and it worked fine

**Comment by ZorinFoss** [comment]
Hi @AminBhst. The problem still exist. i test it on brave and thorium browser and the extension did not detect file download.

**Comment by AminBhst** [comment]
@ZorinFoss on Arch right?

**Comment by ZorinFoss** [comment]
> @ZorinFoss on Arch right?

yes

**Comment by AminBhst** [comment]
@ZorinFoss Hey sorry again for the late response. [Brisk v2.0.0](https://github.com/AminBhst/brisk/releases/tag/v2.0.0) is released. Please test it out and let me know if the problem is fixed or does it still persist

**Comment by ZorinFoss** [comment]
Congratulations on releasing v2. the problem has been fixed.

**Comment by AminBhst** [comment]
@ZorinFoss Thank you. 
By the way, does your friend who manages the arch aur have a github profile or anything? I'd like to credit him for his work if that's possible
